package com.cs2.volunteer_hub.model

enum class Interest {
    // Social Causes
    POVERTY_ALLEVIATION,
    HOMELESSNESS,
    HUNGER_RELIEF,
    AFFORDABLE_HOUSING,
    SOCIAL_JUSTICE,
    HUMAN_RIGHTS,
    REFUGEE_SUPPORT,
    IMMIGRATION,

    // Education & Youth
    EDUCATION,
    YOUTH_DEVELOPMENT,
    LITERACY,
    AFTER_SCHOOL_PROGRAMS,
    MENTORSHIP,
    SCHOLARSHIP_PROGRAMS,
    EARLY_CHILDHOOD_EDUCATION,
    ADULT_EDUCATION,

    // Health & Wellness
    HEALTHCARE,
    MENTAL_HEALTH,
    DISABILITY_SUPPORT,
    ELDERLY_CARE,
    HOSPICE_CARE,
    ADDICTION_RECOVERY,
    CHRONIC_ILLNESS_SUPPORT,
    PUBLIC_HEALTH,
    NUTRITION,
    FITNESS_WELLNESS,

    // Environment & Sustainability
    ENVIRONMENTAL_CONSERVATION,
    CLIMATE_CHANGE,
    RECYCLING,
    RENEWABLE_ENERGY,
    WILDLIFE_PROTECTION,
    OCEAN_CONSERVATION,
    FOREST_CONSERVATION,
    SUSTAINABLE_AGRICULTURE,
    WATER_CONSERVATION,
    POLLUTION_REDUCTION,

    // Animals
    ANIMAL_WELFARE,
    ANIMAL_RESCUE,
    PET_ADOPTION,
    WILDLIFE_REHABILITATION,
    FARM_ANIMAL_PROTECTION,
    MARINE_ANIMAL_CONSERVATION,

    // Arts & Culture
    ARTS_CULTURE,
    MUSIC,
    THEATER,
    MUSEUMS,
    LIBRARIES,
    CULTURAL_PRESERVATION,
    HERITAGE_CONSERVATION,
    PUBLIC_ART,

    // Community Development
    COMMUNITY_BUILDING,
    NEIGHBORHOOD_IMPROVEMENT,
    URBAN_PLANNING,
    RURAL_DEVELOPMENT,
    ECONOMIC_DEVELOPMENT,
    SMALL_BUSINESS_SUPPORT,

    // Children & Families
    CHILD_WELFARE,
    FOSTER_CARE,
    FAMILY_SUPPORT,
    PARENTING_EDUCATION,
    CHILD_PROTECTION,
    SINGLE_PARENT_SUPPORT,

    // Seniors & Aging
    SENIOR_SERVICES,
    ELDER_ABUSE_PREVENTION,
    RETIREMENT_COMMUNITY,
    ALZHEIMERS_SUPPORT,
    AGING_IN_PLACE,

    // Women & Girls
    WOMENS_RIGHTS,
    GIRLS_EMPOWERMENT,
    GENDER_EQUALITY,
    DOMESTIC_VIOLENCE_PREVENTION,
    MATERNAL_HEALTH,
    WOMEN_ENTREPRENEURSHIP,

    // Veterans & Military
    VETERANS_SUPPORT,
    MILITARY_FAMILIES,
    PTSD_SUPPORT,
    VETERAN_EMPLOYMENT,

    // Emergency & Disaster
    DISASTER_RELIEF,
    EMERGENCY_RESPONSE,
    SEARCH_AND_RESCUE,
    DISASTER_PREPAREDNESS,
    HUMANITARIAN_AID,

    // Sports & Recreation
    SPORTS_RECREATION,
    YOUTH_SPORTS,
    ADAPTIVE_SPORTS,
    OUTDOOR_RECREATION,
    COMMUNITY_SPORTS,

    // Technology & Innovation
    DIGITAL_LITERACY,
    TECH_EDUCATION,
    OPEN_SOURCE,
    INNOVATION,
    STEM_EDUCATION,

    // Legal & Advocacy
    LEGAL_AID,
    CIVIL_RIGHTS,
    ADVOCACY,
    POLICY_REFORM,
    VOTER_REGISTRATION,
    CRIMINAL_JUSTICE_REFORM,

    // Faith & Spirituality
    FAITH_BASED,
    INTERFAITH_DIALOGUE,
    SPIRITUAL_CARE,
    RELIGIOUS_EDUCATION,

    // International & Global
    INTERNATIONAL_DEVELOPMENT,
    GLOBAL_HEALTH,
    MICROFINANCE,
    FAIR_TRADE,
    PEACE_BUILDING,
    CONFLICT_RESOLUTION,

    // LGBTQ+
    LGBTQ_RIGHTS,
    LGBTQ_YOUTH_SUPPORT,
    PRIDE_EVENTS,
    TRANSGENDER_SUPPORT,

    // Employment & Career
    JOB_TRAINING,
    CAREER_COUNSELING,
    EMPLOYMENT_SERVICES,
    WORKFORCE_DEVELOPMENT,
    ENTREPRENEURSHIP,

    // Food & Nutrition
    FOOD_BANKS,
    COMMUNITY_GARDENS,
    FOOD_SECURITY,
    NUTRITION_EDUCATION,
    SOUP_KITCHENS,
    MEALS_ON_WHEELS,

    // Housing & Shelter
    HOMELESS_SHELTERS,
    TRANSITIONAL_HOUSING,
    HOME_REPAIR,
    HABITAT_BUILDING,

    // Volunteerism & Civic Engagement
    VOLUNTEER_MANAGEMENT,
    CIVIC_ENGAGEMENT,
    COMMUNITY_SERVICE,
    BOARD_GOVERNANCE,
    NONPROFIT_LEADERSHIP
}


